theme: jekyll-theme-minimal
title: Scala-TS
description: Simple tool which can generate TypeScript from Scala
show_downloads: false
latest_release: 0.5.11
scala_major_version: 2.13
logo: assets/img/logo.png
